let configurationSteps = [
  'Initialized npm project (created package.json)',
  'Initialized local repository',
  'Created repository on github',
  'Connected local repository with remote repository',
  'First commit',
  'First push to github',
  'Project structure (folders "src" and "public")',
  'Created index.html',
  'Basic layout of index.html',
  'Installed react in dependencies (react--loose-envify--js-tokens)',
  'Installed react-dom in dependencies (react-dom--loose-envify--scheduller)',
  'Installed @babel/core, @babel/preset-env, @babel/preset-react in devDependencies (+167 packages)',
  'Installed webpack, webpack-cli, webpack-dev-server in dev-dependencies (+303 packages)',
  'Installed html-webpack-plugin, style-loader, css-loader, babel-loader in dev-dependencies (+61 packages)',
  'Configurated babel',
  'Configurated webpack',
  'Created index.js and react-component App in "src" directory',
  'Added scripts "start" and "build" in webpack.config',
  'Tested commands "npm start" and "npm run build"',
  'Prettier - Code formatter installed for code redactor (extension for Visual Studio Code)',
  'Installed prettier in dev-dependencies (+1 package)',
  'Installed sass and in dev-dependencies sass-loader (+3 packages)',
  'Installed bootstrap in dependencies (+1 package)',
  'Plugged prettier configuration file',
];

export default configurationSteps;
